# Generated by Django 4.0.3 on 2022-07-04 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('first_name', models.CharField(default='Nguyen', max_length=40)),
                ('last_name', models.CharField(default='Tuyet', max_length=40)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(default='0123456789', max_length=10)),
                ('address', models.CharField(default='Viet Nam', max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.BooleanField(default=True)),
                ('role', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
