# Generated by Django 4.0.3 on 2022-07-04 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('idPose', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('times', models.IntegerField(default=0)),
                ('image1', models.ImageField(default=None, upload_to='images')),
                ('image2', models.ImageField(default=None, upload_to='images')),
                ('image3', models.ImageField(default=None, upload_to='images')),
                ('image4', models.ImageField(default=None, upload_to='images')),
                ('image5', models.ImageField(default=None, upload_to='images')),
                ('image6', models.ImageField(default=None, upload_to='images')),
                ('image7', models.ImageField(default=None, upload_to='images')),
                ('image8', models.ImageField(default=None, upload_to='images')),
                ('image9', models.ImageField(default=None, upload_to='images')),
                ('image10', models.ImageField(default=None, upload_to='images')),
                ('advantage', models.TextField()),
                ('excepts', models.TextField()),
                ('exercise', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pose_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('Check', models.CharField(max_length=40)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
    ]
